import { describe, expect, it } from 'vitest';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { InMemoryTransport } from '@modelcontextprotocol/sdk/inMemory.js';
import { mkdtemp, readFile, stat, rm, writeFile, symlink } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { loadConfig } from '../src/config.js';
import { TestimonialClient } from '../src/api/client.js';
import {createApp} from '../src/app.js';import {connect as slipwayConnect} from '@thenavidm/slipway/testing';

/** The write policy comes from the environment on Slipway, as it does in use: this is the one a config describes. */
function policy(prefix:string,config:{readOnly?:boolean;allowDestructive?:boolean;auditPath?:string}):Record<string,string>{return{...(config.readOnly?{[`${prefix}_READ_ONLY`]:'1'}:{}),...(config.allowDestructive===false?{[`${prefix}_ALLOW_DESTRUCTIVE`]:'0'}:{}),...(config.auditPath?{[`${prefix}_AUDIT_LOG`]:config.auditPath}:{})};}
/** Slipway's schema check answers in the MCP SDK's own plain text, "Input validation error: …"; these tests read every error as JSON, so it is wrapped as {error}. */
function jsonError(r:any){const text=r.content?.[0]?.text??'';try{JSON.parse(text);return r;}catch{return{...r,content:[{type:'text',text:JSON.stringify({error:text})}]};}}
/** The SDK client's calls these tests were written against, over the real Slipway server. A hidden tool is a protocol error there; it comes back as the error result a client sees. */
function adapt(mcp:Awaited<ReturnType<typeof slipwayConnect>>){return{listTools:async()=>({tools:await mcp.listTools()}),callTool:async({name,arguments:args}:{name:string;arguments?:Record<string,unknown>}):Promise<any>=>{try{const r:any=await mcp.callTool(name,args??{});return r.isError?jsonError(r):r;}catch(e){return{isError:true,content:[{type:'text',text:JSON.stringify({error:(e as Error).message})}]};}},close:()=>mcp.close()};}
/** One tool call through the real server, as the 2.x guard-and-handler helper made it: the result's data, or its error thrown. */
async function viaServer(prefix:string,config:any,client:any,name:string,args:Record<string,unknown>):Promise<any>{const mcp=await slipwayConnect(createApp({context:()=>({config,client})}),{env:policy(prefix,config)});try{const r:any=await mcp.callTool(name,args);const text=(r.content as any[])?.[0]?.text??'';if(r.isError)throw new Error(text);try{return JSON.parse(text);}catch{return text;}}finally{await mcp.close();}}
type Call={url:URL;init:RequestInit};
async function fixture(options:{readOnly?:boolean;key?:boolean;responder?:(call:Call,index:number)=>Response|Promise<Response>}={}){
 const calls:Call[]=[];const config=loadConfig({TESTIMONIAL_MIN_REQUEST_INTERVAL_MS:'0',...(options.key===false?{}:{TESTIMONIAL_API_KEY:'fixture-key-a'}),...(options.readOnly?{TESTIMONIAL_READ_ONLY:'1'}:{})});
 const api=new TestimonialClient(config,(async(url:any,init:RequestInit)=>{const c={url:new URL(String(url)),init};calls.push(c);return options.responder?.(c,calls.length-1)??Response.json({status:'success'});})as typeof fetch);
 const mcp=await slipwayConnect(createApp({context:()=>({config,client:api})}),{env:policy('TESTIMONIAL',config)});const client=adapt(mcp);
 return{calls,api,client,call:async(name:string,args:Record<string,any>={})=>{const result=await client.callTool({name,arguments:args});return{result,value:JSON.parse((result.content as any[])[0].text)};},close:()=>mcp.close()};
}
const text={name:'Fixture Person',testimonial:'Existing authorized fixture statement'};
const email={name:'Fixture Person',email:'fixture@example.com',spaceName:'Fixture product',adminName:'Fixture owner'};
describe('current native REST and local approval',()=>{
 it('discovers ten shared tools and five reads without credentials',async()=>{const f=await fixture({key:false});try{const {tools}=await f.client.listTools();expect(tools).toHaveLength(10);expect(tools.filter(t=>t.annotations?.readOnlyHint)).toHaveLength(5);expect((await f.call('list_accounts')).value).toEqual({accounts:[]});expect(f.calls).toHaveLength(0);}finally{await f.close();}});
 it('uses one Space array, exact query names and repeated OR tag names',async()=>{const f=await fixture({responder:()=>Response.json([{id:'fixture'}])});try{expect((await f.call('list_testimonials',{type:'text',liked:false,highlighted:true,tag:['First tag','Second tag'],limit:7})).value).toEqual([{id:'fixture'}]);const c=f.calls[0]!;expect(c.url.origin).toBe('https://api.testimonial.to');expect(c.url.pathname).toBe('/v1/testimonials');expect(c.url.searchParams.getAll('tag')).toEqual(['First tag','Second tag']);expect(c.url.searchParams.get('liked')).toBe('false');expect((c.init.headers as any).Authorization).toBe('Bearer fixture-key-a');expect(c.init.redirect).toBe('error');}finally{await f.close();}});
 it.each([{page:1},{per_page:25},{offset:1},{spaceId:'fixture'},{tag:'one'}])('refuses stale list argument %j',async args=>{const f=await fixture();try{expect((await f.call('list_testimonials',args)).result.isError).toBe(true);expect(f.calls).toHaveLength(0);}finally{await f.close();}});
 it('rejects stale or invalid list response envelopes',async()=>{const f=await fixture({responder:()=>Response.json({data:[]})});try{expect((await f.call('list_testimonials')).result.isError).toBe(true);expect(f.calls).toHaveLength(1);}finally{await f.close();}});
 it('does not interpret local confirm as customer public-use consent',async()=>{const f=await fixture();try{expect((await f.call('submit_text_testimonial',{...text,confirm:true})).result.isError).toBeFalsy();expect(JSON.parse(f.calls[0]!.init.body as string)).toEqual({...text,confirm:false,isLiked:false});expect(f.calls[0]!.url.pathname).toBe('/v1/submit/text');}finally{await f.close();}});
 it('maps explicit customer consent separately and retains native fields',async()=>{const f=await fixture();try{expect((await f.call('submit_text_testimonial',{...text,rating:5,customer_consent:true,isLiked:true,confirm:true})).result.isError).toBeFalsy();expect(JSON.parse(f.calls[0]!.init.body as string)).toEqual({...text,rating:5,confirm:true,isLiked:true});}finally{await f.close();}});
 it.each([{}, {customer_consent:false}])('refuses Wall of Love without actual customer consent %j',async extra=>{const f=await fixture();try{expect((await f.call('submit_text_testimonial',{...text,...extra,isLiked:true,confirm:true})).result.isError).toBe(true);expect(f.calls).toHaveLength(0);}finally{await f.close();}});
 it('native payload consent does not approve the local operation',async()=>{const f=await fixture();try{expect((await f.call('submit_text_testimonial',{payload:{...text,confirm:true,isLiked:true}})).result.isError).toBe(true);expect(f.calls).toHaveLength(0);expect((await f.call('submit_text_testimonial',{payload:{...text,confirm:true,isLiked:true},confirm:true})).result.isError).toBeFalsy();expect(JSON.parse(f.calls[0]!.init.body as string).confirm).toBe(true);}finally{await f.close();}});
 it('rejects mixing customer-consent/body flags and payload',async()=>{const f=await fixture();try{expect((await f.call('submit_text_testimonial',{payload:text,customer_consent:true,confirm:true})).result.isError).toBe(true);expect(f.calls).toHaveLength(0);}finally{await f.close();}});
 it.each([{customerName:'Old name',text:'Old text',spaceId:'fixture'},{name:' ',testimonial:'text'},{name:'Fixture',testimonial:' '},{...text,rating:6},{...text,avatarURL:'http://example.com/a.png'},{...text,avatarURL:'https://key:password@example.com/a.png'}])('refuses obsolete/invalid submit fields %j',async args=>{const f=await fixture();try{expect((await f.call('submit_text_testimonial',{...args,confirm:true})).result.isError).toBe(true);expect(f.calls).toHaveLength(0);}finally{await f.close();}});
 it('submits video with native videoURL and separate consent',async()=>{const f=await fixture();try{expect((await f.call('submit_video_testimonial',{name:'Fixture',videoURL:'https://example.com/video.mp4',confirm:true})).result.isError).toBeFalsy();expect(f.calls[0]!.url.pathname).toBe('/v1/submit/video');expect(JSON.parse(f.calls[0]!.init.body as string)).toEqual({name:'Fixture',videoURL:'https://example.com/video.mp4',confirm:false,isLiked:false});}finally{await f.close();}});
 it('requires explicit approval for a side-effecting GET email',async()=>{const f=await fixture();try{expect((await f.call('send_testimonial_request',email)).result.isError).toBe(true);expect(f.calls).toHaveLength(0);expect((await f.call('send_testimonial_request',{...email,confirm:true})).result.isError).toBeFalsy();const c=f.calls[0]!;expect(c.init.method).toBe('GET');expect(c.init.body).toBeUndefined();expect(c.url.pathname).toBe('/v1/new/request');for(const[k,v]of Object.entries(email))expect(c.url.searchParams.get(k)).toBe(v);expect(c.url.searchParams.has('confirm')).toBe(false);}finally{await f.close();}});
 it.each(['name','email','spaceName','adminName'])('requires actual native email parameter %s',async missing=>{const f=await fixture();try{const args:any={...email,confirm:true};delete args[missing];expect((await f.call('send_testimonial_request',args)).result.isError).toBe(true);expect(f.calls).toHaveLength(0);}finally{await f.close();}});
 it('hides effects and directly refuses email GET and consent-approved imports',async()=>{const f=await fixture({readOnly:true});try{expect((await f.client.listTools()).tools).toHaveLength(5);for(const[name,args]of[['send_testimonial_request',email],['submit_text_testimonial',{...text,customer_consent:true}],['export_testimonials',{output_file:join(tmpdir(),'unused-testimonial-fixture.json')}]]as const){expect(JSON.stringify((await f.call(name,{...args,confirm:true})).value)).toMatch(/READ_ONLY|not found/);}expect(f.calls).toHaveLength(0);}finally{await f.close();}});
 it('rejects HTTP200 native failed receipts without retry',async()=>{const f=await fixture({responder:()=>Response.json({status:'failed',message:'fixture-key-a rejected'})});try{const r=await f.call('submit_text_testimonial',{...text,confirm:true});expect(r.result.isError).toBe(true);expect(JSON.stringify(r.value)).not.toContain('fixture-key-a');expect(f.calls).toHaveLength(1);}finally{await f.close();}});
 it.each([401,429,500])('does not retry native HTTP %s',async status=>{const f=await fixture({responder:()=>Response.json({message:'fixture-key-a error'},{status})});try{expect((await f.call('send_testimonial_request',{...email,confirm:true})).result.isError).toBe(true);expect(f.calls).toHaveLength(1);}finally{await f.close();}});
 it('refuses arbitrary URLs and old update/submit routes',async()=>{const f=await fixture();try{for(const[method,path]of[['GET','https://example.com'],['PUT','/testimonials/fixture'],['POST','/testimonials/text'],['GET','/testimonials/../verify']])await expect(f.api.request(method!,path!)).rejects.toThrow();expect(f.calls).toHaveLength(0);}finally{await f.close();}});
});
describe('profile isolation and exact reviewed work',()=>{
 it('named Space profiles never inherit a global key',()=>{const c=loadConfig({TESTIMONIAL_API_KEY:'global-fixture',TESTIMONIAL_ACCOUNTS:'[{"name":"explicit"}]'});expect(c.accounts[0]!.apiToken).toBe('');});
 it.each([{TESTIMONIAL_ACCOUNTS:'[{"name":"a"},{"name":"a"}]'},{TESTIMONIAL_API_KEY:'fixture',TESTIMONIAL_TOKEN_FILE:'/private/tmp/fixture'},{TESTIMONIAL_ACCOUNTS:'[{"name":"a","api_key":"fixture","other":"x"}]'}])('refuses ambiguous private profile %j',env=>expect(()=>loadConfig(env)).toThrow());
 it('prevalidates every customer consent field before first request',async()=>{const f=await fixture();try{const tasks=[{tool:'submit_text_testimonial',arguments:text},{tool:'submit_text_testimonial',arguments:{...text,isLiked:true}}];expect((await f.call('preview_testimonial_batch',{tasks})).result.isError).toBe(true);expect(f.calls).toHaveLength(0);}finally{await f.close();}});
 it('hash binds consent and exact ordered request contents',async()=>{const f=await fixture();try{const tasks=[{tool:'submit_text_testimonial',arguments:text}];const p=await f.call('preview_testimonial_batch',{tasks});expect(p.result.isError).toBeFalsy();expect(f.calls).toHaveLength(0);const changed=[{tool:'submit_text_testimonial',arguments:{...text,customer_consent:true}}];expect((await f.call('submit_testimonial_batch',{tasks:changed,review_sha256:p.value.reviewSha256,confirm:true})).result.isError).toBe(true);expect(f.calls).toHaveLength(0);}finally{await f.close();}});
 it('refuses nested local approval/account/file overrides',async()=>{const f=await fixture();try{for(const extra of[{confirm:true},{account:'other'},{payload_file:'/private/tmp/fixture.json'}])expect((await f.call('preview_testimonial_batch',{tasks:[{tool:'submit_text_testimonial',arguments:{...text,...extra}}]})).result.isError).toBe(true);expect(f.calls).toHaveLength(0);}finally{await f.close();}});
 it('stops on a native failed receipt with exact partial outcomes',async()=>{const f=await fixture({responder:(_,i)=>Response.json(i===1?{status:'failed',message:'Fixture failure'}:{status:'success'})});try{const tasks=Array.from({length:3},(_,i)=>({tool:'submit_text_testimonial',arguments:{...text,name:`Fixture${i}`}}));const p=await f.call('preview_testimonial_batch',{tasks});const r=await f.call('submit_testimonial_batch',{tasks,review_sha256:p.value.reviewSha256,confirm:true});expect(r.result.isError).toBe(true);const receipt=JSON.parse(r.value.error);expect(receipt.failedIndex).toBe(1);expect(receipt.knownResults).toHaveLength(1);expect(receipt.unattemptedIndices).toEqual([2]);expect(f.calls).toHaveLength(2);}finally{await f.close();}});
});
describe('single-response bounded private export',()=>{
 it('writes one private JSON array and never asserts complete backup or pagination',async()=>{const dir=await mkdtemp(join(tmpdir(),'testimonial-export-'));const f=await fixture({responder:()=>Response.json([{id:'one'},{id:'two'}])});try{const output_file=join(dir,'proof.json');const r=await f.call('export_testimonials',{output_file,limit:2,confirm:true});expect(r.result.isError).toBeFalsy();expect(r.value.requests).toBe(1);expect(r.value.atNativeLimit).toBe(true);expect(r.value.completeBackup).toBe(false);expect(r.value.paginationSupported).toBe(false);expect(f.calls).toHaveLength(1);expect(f.calls[0]!.url.searchParams.has('page')).toBe(false);expect(JSON.parse(await readFile(output_file,'utf8')).testimonials).toHaveLength(2);if(process.platform!=='win32')expect((await stat(output_file)).mode&0o777).toBe(0o600);}finally{await f.close();await rm(dir,{recursive:true,force:true});}});
 it('does not overwrite existing files or issue a request',async()=>{const dir=await mkdtemp(join(tmpdir(),'testimonial-export-'));const f=await fixture();try{const output_file=join(dir,'existing.json');await writeFile(output_file,'original');expect((await f.call('export_testimonials',{output_file,confirm:true})).result.isError).toBe(true);expect(f.calls).toHaveLength(0);expect(await readFile(output_file,'utf8')).toBe('original');}finally{await f.close();await rm(dir,{recursive:true,force:true});}});
 it.each([{data:[]},[{id:'one'},{id:'two'}]])('cleans up only the newly created file on invalid/oversized array %j',async receipt=>{const dir=await mkdtemp(join(tmpdir(),'testimonial-export-'));const f=await fixture({responder:()=>Response.json(receipt)});try{const output_file=join(dir,'partial.json');expect((await f.call('export_testimonials',{output_file,limit:1,confirm:true})).result.isError).toBe(true);await expect(stat(output_file)).rejects.toThrow();expect(f.calls).toHaveLength(1);}finally{await f.close();await rm(dir,{recursive:true,force:true});}});
 it('rejects response bytes over cap without retained output',async()=>{const dir=await mkdtemp(join(tmpdir(),'testimonial-export-'));const f=await fixture({responder:()=>Response.json([{text:'x'.repeat(5*1048576)}])});try{const output_file=join(dir,'large.json');expect((await f.call('export_testimonials',{output_file,confirm:true})).result.isError).toBe(true);await expect(stat(output_file)).rejects.toThrow();expect(f.calls).toHaveLength(1);}finally{await f.close();await rm(dir,{recursive:true,force:true});}});
});
