import operationsData from'./operations.json'with{type:'json'};import provenance from'./provenance.json'with{type:'json'};import{Ajv,type ValidateFunction}from'ajv';import addFormats from'ajv-formats';import{open,lstat,unlink}from'node:fs/promises';import{constants}from'node:fs';import{isAbsolute}from'node:path';import{createHash}from'node:crypto';
import{TestimonialClient,type Json,type QueryParam}from'../api/client.js';import{TestimonialError,UsageError}from'../api/errors.js';import{selectAccount,type Config}from'../config.js';import type{Risk}from'../safety.js';
export type Operation={name:string;operationId:string;title:string;description:string;method:string;path:string;group:string;risk:Risk;params:{name:string;key:string;in:string;required:boolean;schema:Json;style:string;explode:boolean}[];bodySchema:Json|null;bodyRequired:boolean;privateOutput:boolean};
export type ToolSpec={name:string;title:string;description:string;group:string;inputSchema:Json;risk:Risk;handler:(args:Json,client:TestimonialClient)=>Promise<unknown>};
const operations=operationsData as unknown as Operation[];const ajv=new Ajv({allErrors:true,strict:false,formats:{int64:true}});(addFormats as unknown as(a:Ajv)=>void)(ajv);
const bodyValidators=new Map(operations.filter(o=>o.bodySchema).map(o=>[o.name,ajv.compile(o.bodySchema!)]));
function check(v:ValidateFunction,a:unknown){if(!v(a))throw new UsageError(ajv.errorsText(v.errors,{separator:'; '}));}
function fieldsFor(op:Operation){const properties:Json=Object.fromEntries(op.params.map(p=>[p.key,p.schema]));for(const [k,v] of Object.entries(op.bodySchema?.properties??{}))properties[k==='confirm'?'customer_consent':k]=v;properties.account={type:'string',description:'Exact configured private account profile label; not a tenant or provider account ID.'};if(op.risk!=='read')properties.confirm={type:'boolean',description:'Must be true for the requested mutation or exclusive private output file.'};if(op.bodySchema){properties.payload={...op.bodySchema,description:'Complete native testimonial JSON object; do not mix with body flags or payload_file.'};properties.payload_file={type:'string',minLength:1,description:'Absolute regular non-symlink JSON body file, at most 1 MiB. Cannot mix with payload/body flags.'};}if(op.privateOutput)properties.output_file={type:'string',minLength:1,description:'Required absolute new private file. Exclusive 0600 creation; never overwrites or echoes PNG/embed credentials.'};return{type:'object',properties,required:[...op.params.filter(p=>p.required).map(p=>p.key),...(op.privateOutput?['output_file']:[])],additionalProperties:false};}
async function fileJSON(path:string){let f;try{if(!isAbsolute(path)||(await lstat(path)).isSymbolicLink())throw Error();f=await open(path,constants.O_RDONLY|(constants.O_NOFOLLOW??0));const stat=await f.stat();if(!stat.isFile()||stat.size>1048576)throw Error();return JSON.parse(await f.readFile('utf8'));}catch{throw new UsageError('payload_file must be an absolute regular non-symlink JSON body file, at most 1 MiB.');}finally{await f?.close();}}
function semantics(op:Operation,args:Json,body:any){
 if(op.bodySchema){
  for(const key of ['name','testimonial','title'])if(body[key]!==undefined&&!body[key].trim())throw new UsageError('Provided '+key+' cannot be blank.');
  body.confirm=body.confirm??false;body.isLiked=body.isLiked??false;
  if(body.isLiked&&body.confirm!==true)throw new UsageError('Wall of Love requires actual customer public-use consent; local confirm does not provide it.');
  for(const key of ['videoURL','avatarURL','attachedImageURL'])if(body[key]!==undefined){let u;try{u=new URL(body[key]);}catch{throw new UsageError('Invalid media URL.');}if(u.protocol!=='https:'||u.username||u.password)throw new UsageError('Media URLs must use HTTPS without embedded credentials.');}
 }
 if(op.name==='send_testimonial_request')for(const key of ['name','spaceName','adminName'])if(!args[key].trim())throw new UsageError('Email context '+key+' cannot be blank.');
}
async function prepare(op:Operation,args:Json){const flat=Object.fromEntries(Object.keys(op.bodySchema?.properties??{}).filter(k=>args[k==='confirm'?'customer_consent':k]!==undefined).map(k=>[k,args[k==='confirm'?'customer_consent':k]]));if((args.payload!==undefined||args.payload_file!==undefined)&&Object.keys(flat).length)throw new UsageError('Do not mix body flags with payload/payload_file.');if(args.payload!==undefined&&args.payload_file!==undefined)throw new UsageError('Use payload or payload_file, not both.');let body=op.bodySchema?(args.payload_file?await fileJSON(args.payload_file):args.payload??flat):undefined;if(op.bodyRequired&&args.payload===undefined&&!args.payload_file&&!Object.keys(flat).length)throw new UsageError('This operation requires a native body; inspect schema and provide body flags, payload or payload_file.');if(op.bodySchema)check(bodyValidators.get(op.name)!,body);semantics(op,args,body);const path=op.params.filter(p=>p.in==='path').reduce((s,p)=>s.replace('{'+p.name+'}',encodeURIComponent(String(args[p.key]))),op.path);const query:QueryParam[]=op.params.filter(p=>p.in==='query'&&args[p.key]!==undefined).map(p=>({name:p.name,value:args[p.key],explode:p.explode}));return{method:op.method,path,query,body};}
async function execute(op:Operation,args:Json,client:TestimonialClient){const call=await prepare(op,args);const result=await client.request(call.method,call.path,call.query,call.body,args.account);if(op.name==='list_testimonials'&&!Array.isArray(result))throw new TestimonialError('Invalid native testimonial array.');return client.sanitize(result);}
export const ALL_TOOLS:ToolSpec[]=operations.map(op=>({...op,inputSchema:fieldsFor(op),handler:(args,client)=>execute(op,args,client)}));
const account={type:'string',description:'Exact selected private account profile; binds label, not key ownership.'};const confirm={type:'boolean',description:'Explicit approval for this exact requested ordered batch.'};
function helper(name:string,title:string,description:string,risk:Risk,properties:Json,required:string[],handler:ToolSpec['handler']){ALL_TOOLS.push({name,title,description,group:'local_workflows',risk,inputSchema:{type:'object',properties,required,additionalProperties:false},handler});}
helper('list_accounts','List configured accounts','Local profile labels/default/auth method only. No keys, token paths, provider identity or network request.','read',{},[],async(_,c)=>({accounts:c.config.accounts.map(a=>({name:a.name,default:a.name===c.config.defaultAccount,auth:a.apiToken||a.tokenFile?'api_key':'not_configured',credentialSource:a.tokenFile?'token_file':a.apiToken?'private_setting':'not_configured'}))}));
helper('get_operation_schema','Inspect a current native operation','Local reviewed method/path/query/body schema and provenance for one native tool. No credentials or provider request.','read',{operation:{type:'string',enum:operations.map(o=>o.name),description:'Exact native tool name, e.g. submit_text_testimonial or send_testimonial_request.'}},['operation'],async a=>({operation:operations.find(o=>o.name===a.operation),source:provenance.source,checked:provenance.checked,snapshotSha256:provenance.sanitizedSnapshotSha256}));
const allowed=operations.filter(o=>o.risk!=='read'&&o.group==='testimonials').map(o=>o.name);
const tasks={type:'array',minItems:1,maxItems:20,description:'One to twenty exact ordered supported text/video import/email operations. Each task is one exact native import or one email request. Customer consent is separate from local approval.',items:{type:'object',properties:{tool:{type:'string',enum:allowed},arguments:{type:'object',description:'Actual native tool arguments without account, confirm, payload_file or output_file.'}},required:['tool','arguments'],additionalProperties:false}};
function canonical(v:any):any{if(Array.isArray(v))return v.map(canonical);if(v&&typeof v==='object')return Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonical(v[k])]));return v;}
function hash(v:any){return createHash('sha256').update(JSON.stringify(canonical(v))).digest('hex');}
async function reviewed(args:Json,c:TestimonialClient){const selected=selectAccount(c.config,args.account);const calls=[];for(const task of args.tasks){if(!allowed.includes(task.tool))throw new UsageError('Unsupported testimonial batch tool.');if(['account','confirm','payload_file','output_file'].some(k=>task.arguments[k]!==undefined))throw new UsageError('Batch arguments cannot override account/confirmation or reference mutable payload files.');const t=ALL_TOOLS.find(t=>t.name===task.tool)!,op=operations.find(o=>o.name===task.tool)!;validateArguments(t,task.arguments);calls.push(await prepare(op,task.arguments));}return{version:1,profile:selected.name,authType:'api_key',snapshotSha256:provenance.sanitizedSnapshotSha256,tasks:args.tasks,calls};}
helper('preview_testimonial_batch','Review exact ordered testimonial tasks','Local validation and SHA-256 of exact ordered text/video import/email work, selected profile label and reviewed schema. No provider reads, key load, identity check, price or rollback guarantee.','read',{tasks,account},['tasks'],async(a,c)=>{const r=await reviewed(a,c);return{...c.sanitize(r)as Json,reviewSha256:hash(r),localOnly:true,providerValidated:false,notice:'Binds profile label and exact requests/order/schema, not key ownership or changing provider state. Each request can import one testimonial or send one email. Preview is local input review, not a real cohort count or provider approval token.'};});
helper('submit_testimonial_batch','Execute reviewed testimonial tasks','Confirmed one-to-twenty ordered text/video import/email tasks. Prevalidate all and verify exact hash before first request. Stop on first failure with known results/failed index/unattempted indices; no retries, rollback or implicit continuation.','destructive',{tasks,account,confirm,review_sha256:{type:'string',pattern:'^[a-f0-9]{64}$',description:'Exact preview_testimonial_batch hash for identical requests, profile label, schema and order.'}},['tasks','review_sha256'],async(a,c)=>{const r=await reviewed(a,c);if(hash(r)!==a.review_sha256)throw new UsageError('Review hash mismatch; preview these exact tasks and selected profile again.');const knownResults:Json[]=[];for(let i=0;i<r.calls.length;i++){const call=r.calls[i]!;try{const result=c.sanitize(await c.request(call.method,call.path,call.query,call.body,r.profile));knownResults.push({index:i,tool:a.tasks[i].tool,result});}catch(e){const err=e as TestimonialError;throw new TestimonialError(JSON.stringify(c.sanitize({notice:'Batch stopped. Failed request may have an unknown outcome; inspect provider state before repeating. No retries or rollback.',knownResults,failedIndex:i,unattemptedIndices:r.calls.slice(i+1).map((_,j)=>i+1+j),error:err.message})),err.status??0,err.code??'API_ERROR');}}return{requestsProcessed:true,knownResults,notice:'Native requests returned; Provider video processing and emailed requests may continue separately. A successful receipt is not processing completion, email delivery or consent proof.'};});
const listOp=operations.find(o=>o.name==='list_testimonials')!;
helper('export_testimonials','Export one bounded private testimonial array','Confirmed single native GET saved to a new exclusive mode 0600 JSON file, default limit 100/local maximum 10,000 and 5 MiB response/file cap. No pagination, continuation, media download, overwrite or atomic complete-backup claim.','destructive',{...fieldsFor(listOp).properties,confirm:{type:'boolean',description:'Explicit approval to save this bounded response to a new private file.'},output_file:{type:'string',minLength:1,description:'Absolute new file in an existing private directory; restrict Windows ACLs separately.'}},['output_file'],async(a,c)=>{
 if(!isAbsolute(a.output_file))throw new UsageError('output_file must be absolute.');
 const limit=a.limit??100;const call=await prepare(listOp,{...a,limit});let f;try{f=await open(a.output_file,'wx',0o600);}catch{throw new UsageError('Cannot exclusively create output_file.');}
 try{const testimonials=await c.request(call.method,call.path,call.query,call.body,a.account);if(!Array.isArray(testimonials)||testimonials.length>limit)throw new TestimonialError('Invalid native testimonial array or local result cap exceeded.');const receipt={requests:1,items:testimonials.length,requestedLimit:limit,atNativeLimit:testimonials.length===limit,completeBackup:false,paginationSupported:false,atomicSnapshot:false};const bytes=Buffer.from(JSON.stringify({testimonials:c.sanitize(testimonials),receipt})+'\n');if(bytes.length>5*1048576)throw new TestimonialError('Export exceeds the 5 MiB local cap; no partial file retained.');await f.writeFile(bytes);return{saved:true,output_file:a.output_file,bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex'),...receipt};
 }catch(e){await f.close();f=undefined;await unlink(a.output_file).catch(()=>{});throw e;}finally{await f?.close();}
});
const validators=new Map(ALL_TOOLS.map(t=>[t.name,ajv.compile(t.inputSchema)]));export function validateArguments(tool:ToolSpec,args:Json){check(validators.get(tool.name)!,args);}export function visibleTools(c:Config){return ALL_TOOLS.filter(t=>!c.readOnly||t.risk==='read');}
